# Generated by Django 6.0.7 on 2026-07-17 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "narrative",
                    models.TextField(
                        help_text="Opening scene-setting text shown to the student before the incident starts."
                    ),
                ),
                ("time_limit_seconds", models.PositiveIntegerField(default=600)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["track", "id"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("cybersecurity", "Cybersecurity"),
                            ("software", "Software Engineering"),
                            ("cloud", "Cloud"),
                        ],
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(default="🔐", max_length=10)),
                ("accent_color", models.CharField(default="#ef4444", max_length=20)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("detect", "Detect"),
                            ("assess", "Assess"),
                            ("root_cause", "Root Cause"),
                            ("fix", "Fix"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The question/challenge shown to the student."
                    ),
                ),
                (
                    "artifact",
                    models.TextField(
                        blank=True,
                        help_text="Log snippet, code block, or JSON config shown alongside the prompt.",
                    ),
                ),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice (4 options, deterministic check)"),
                            (
                                "drag_drop",
                                "Drag & Drop Sequence (order items, deterministic check)",
                            ),
                            ("free_text", "Free Text (AI semantic grading)"),
                            ("code_editor", "Code Editor (AI semantic grading)"),
                            ("terminal", "Terminal Simulator (AI semantic grading)"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("mcq_options", models.TextField(blank=True, default="[]")),
                (
                    "drag_items",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON list of draggable items shown to the student in scrambled order.",
                    ),
                ),
                ("correct_answer", models.TextField()),
                (
                    "hint",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the student after a wrong answer.",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="tracks.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "order"],
                "unique_together": {("scenario", "order")},
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_given", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("ai_feedback", models.TextField(blank=True, default="")),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tracks.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scenario",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="tracks.track",
            ),
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "ordering": ["track"],
                "unique_together": {("user", "track")},
            },
        ),
    ]
