# Generated by Django 6.0.7 on 2026-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="lesson_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated lesson explaining the concepts in this scenario.",
            ),
        ),
    ]
